spring.application.name=vastravibe


spring.datasource.url=jdbc:postgresql://localhost:5432/vastravibe_db
spring.datasource.username=postgres
spring.datasource.password=rodbez

# Hibernate automatically creates/updates tables based on entities
spring.jpa.hibernate.ddl-auto=update


# Show SQL queries in console
spring.jpa.show-sql=true